# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
# 控制workflow的执行时机
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # 在master分支被push或pull_request时触发
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # 允许你在Action tabs里手动执行这个workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# 一个workflow由一个或多个jobs组成，他们可以串行或并行执行
jobs:
  # This workflow contains a single job called "build"
  # 这个workflow包含一个名为"build"的job
  build:
    # The type of runner that the job will run on
    # 这个job的运行环境，TODO 改为centos
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Steps是一系列要执行的任务，他们属于job的一部分
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # 运行单行脚本
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # 运行多行脚本
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
